// instructions.h

#ifndef INSTRUCTIONS_H
#define INSTRUCTIONS_H

#include <tchar.h>

const TCHAR instructionsText[] =
_T("VeilPNG by Amadon\r\n")
_T("\r\n")
_T("\"Privacy is necessary for an open society in the electronic age.\"\r\n")
_T("- Eric Hughes, A Cypherpunk's Manifesto\r\n")
_T("\r\n")
_T("VeilPNG is a utility designed to securely hide sensitive data within PNG images using strong encryption and compression techniques. ")
_T("It allows users to embed any file into a PNG image by compressing the data and encrypting it with a password using AES-256-GCM encryption. ")
_T("The encryption key is derived from the password using PBKDF2 with HMAC-SHA256, utilizing a unique salt and high iteration count to enhance security against brute-force attacks. ")
_T("The encrypted data is stored within a custom ancillary chunk in the PNG file format, ensuring the image remains valid while concealing the hidden content. ")
_T("Users can later extract the hidden file by providing the correct password, which also verifies data integrity through an HMAC-SHA256 hash. ")
_T("VeilPNG offers a secure way to transfer private information within seemingly innocuous images.\r\n")
_T("\r\n")
_T("Using VeilPNG\r\n")
_T("\r\n")
_T("Embedding Data into a PNG Image (Creating a Veil)\r\n")
_T("\r\n")
_T("Follow these steps to embed a hidden file into a PNG image:\r\n")
_T("\r\n")
_T("Select the PNG File:\r\n")
_T("Click on the \"Browse...\" button next to the \"PNG File\" field.\r\n")
_T("In the file dialog, navigate to the PNG image you wish to use as the carrier and select it.\r\n")
_T("The path to the PNG file will appear in the \"PNG File\" field.\r\n")
_T("\r\n")
_T("Select the File to Hide:\r\n")
_T("Click on the \"Browse...\" button next to the \"Hidden File\" field.\r\n")
_T("In the file dialog, navigate to the file you wish to embed within the PNG image and select it.\r\n")
_T("The path to the hidden file will appear in the \"Hidden File\" field.\r\n")
_T("\r\n")
_T("Enter a Strong Password:\r\n")
_T("In the \"Password\" field, enter a strong password that will be used to encrypt the hidden data.\r\n")
_T("Password Requirements:\r\n")
_T("- Minimum of 8 characters\r\n")
_T("- Must include at least one uppercase letter\r\n")
_T("- Must include at least one lowercase letter\r\n")
_T("- Must include at least one digit\r\n")
_T("- Must include at least one special character (e.g., !@#$%^&*)\r\n")
_T("Note: Remember this password; you will need it to extract the hidden file later.\r\n")
_T("\r\n")
_T("Show Password (Optional):\r\n")
_T("If you wish to view the password as you type, check the \"Show Password\" checkbox.\r\n")
_T("Uncheck it to hide the password again.\r\n")
_T("\r\n")
_T("Create the Veil:\r\n")
_T("Click on the \"Create Veil\" button.\r\n")
_T("You will be prompted to choose a location and filename for the output PNG image.\r\n")
_T("Choose a directory and enter a filename, then click \"Save\".\r\n")
_T("The application will process the files. A progress bar will indicate the operation status.\r\n")
_T("Upon completion, a message box will confirm that the veil was created successfully.\r\n")
_T("\r\n")
_T("Result:\r\n")
_T("The output PNG image now contains the hidden file.\r\n")
_T("The image remains a valid PNG and can be viewed normally.\r\n")
_T("Important: The hidden data cannot be extracted without the correct password.\r\n")
_T("\r\n")
_T("Extracting Data from a PNG Image (Extracting a Veil)\r\n")
_T("\r\n")
_T("Follow these steps to extract a hidden file from a PNG image:\r\n")
_T("\r\n")
_T("Select the PNG File:\r\n")
_T("Click on the \"Browse...\" button next to the \"PNG File\" field.\r\n")
_T("In the file dialog, navigate to the PNG image containing the hidden data and select it.\r\n")
_T("The path to the PNG file will appear in the \"PNG File\" field.\r\n")
_T("\r\n")
_T("Enter the Password:\r\n")
_T("In the \"Password\" field, enter the password that was used when the data was embedded.\r\n")
_T("Note: The password is case-sensitive.\r\n")
_T("\r\n")
_T("Show Password (Optional):\r\n")
_T("If you wish to verify the password as you type, check the \"Show Password\" checkbox.\r\n")
_T("Uncheck it to hide the password again.\r\n")
_T("\r\n")
_T("Extract the Veil:\r\n")
_T("Click on the \"Extract Veil\" button.\r\n")
_T("You will be prompted to select an output folder where the hidden file will be saved.\r\n")
_T("Choose a directory and click \"OK\".\r\n")
_T("The application will process the PNG file. A progress bar will indicate the operation status.\r\n")
_T("Upon completion, a message box will confirm that the hidden file was extracted successfully, displaying the filename.\r\n")
_T("\r\n")
_T("Result:\r\n")
_T("The hidden file will be saved to the selected output folder.\r\n")
_T("You can now access the file as normal.\r\n")
_T("\r\n")
_T("Best Practices and Tips\r\n")
_T("\r\n")
_T("Use Strong Passwords:\r\n")
_T("Always use a strong, unique password to maximize security.\r\n")
_T("Avoid using easily guessable passwords or common words.\r\n")
_T("\r\n")
_T("Remember Your Password:\r\n")
_T("If you forget the password, you will not be able to extract the hidden data.\r\n")
_T("Consider using a secure password manager to store your passwords.\r\n")
_T("\r\n")
_T("Verify Hidden Data:\r\n")
_T("After embedding data, you may want to extract it immediately to ensure the process was successful.\r\n")
_T("\r\n")
_T("Data Integrity:\r\n")
_T("VeilPNG uses HMAC-SHA256 to verify data integrity during extraction.\r\n")
_T("If the data has been tampered with, the extraction will fail.\r\n")
_T("\r\n")
_T("File Sizes:\r\n")
_T("Be mindful of the size of the hidden file.\r\n")
_T("Large hidden files will increase the size of the PNG image, which may arouse suspicion.\r\n")
;

#endif // INSTRUCTIONS_H
